name: Gh-Pages

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: https://github.com/planemath/frontend/
          webRenderer: canvaskit