name: Deploy Web

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href=/frontend/ --web-renderer canvaskit --no-tree-shake-icons --release 

      - name: Copy files
        run: cp -r build/web/ ./docs