name: Deploy Web

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href=/frontend/ --web-renderer canvaskit --no-tree-shake-icons --release 

      - name: Deploy
        run: |
          git init
          git config --global user.email joaopedrorafael19@gmail.com
          git config --global user.name JoaoRafa19
          git status
          git remote add origin https://${{secrets.token}}@github.com/planemath/frontend.git
          git checkout -b gh-pages
          
          flutter build web --base-href=/frontend/ --web-renderer canvaskit --no-tree-shake-icons --release 
          cp -r build/web/ ./docs
          git add --all
          git commit -m "update"
          
          git push origin gh-pages -f